// Generated by gencpp from file robot_msgs/touch.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_TOUCH_H
#define ROBOT_MSGS_MESSAGE_TOUCH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct touch_
{
  typedef touch_<ContainerAllocator> Type;

  touch_()
    : data()
    , button(0)  {
    }
  touch_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , button(0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;

   typedef int64_t _button_type;
  _button_type button;





  typedef boost::shared_ptr< ::robot_msgs::touch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::touch_<ContainerAllocator> const> ConstPtr;

}; // struct touch_

typedef ::robot_msgs::touch_<std::allocator<void> > touch;

typedef boost::shared_ptr< ::robot_msgs::touch > touchPtr;
typedef boost::shared_ptr< ::robot_msgs::touch const> touchConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::touch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::touch_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robot_msgs': ['/home/master/franka_final_ws/src/teleoperation/robot_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::touch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::touch_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::touch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::touch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::touch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::touch_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::touch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f1272e2491adfe1bf33324ccd3fec13";
  }

  static const char* value(const ::robot_msgs::touch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f1272e2491adfe1ULL;
  static const uint64_t static_value2 = 0xbf33324ccd3fec13ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::touch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/touch";
  }

  static const char* value(const ::robot_msgs::touch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::touch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] data\n"
"int64 button\n"
;
  }

  static const char* value(const ::robot_msgs::touch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::touch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.button);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct touch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::touch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::touch_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "button: ";
    Printer<int64_t>::stream(s, indent + "  ", v.button);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_TOUCH_H
