// Generated by gencpp from file franka_msgs/error_recovery.msg
// DO NOT EDIT!


#ifndef FRANKA_MSGS_MESSAGE_ERROR_RECOVERY_H
#define FRANKA_MSGS_MESSAGE_ERROR_RECOVERY_H

#include <ros/service_traits.h>


#include <franka_msgs/error_recoveryRequest.h>
#include <franka_msgs/error_recoveryResponse.h>


namespace franka_msgs
{

struct error_recovery
{

typedef error_recoveryRequest Request;
typedef error_recoveryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct error_recovery
} // namespace franka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_msgs::error_recovery > {
  static const char* value()
  {
    return "7f352b44c251978f0843cd60887550cf";
  }

  static const char* value(const ::franka_msgs::error_recovery&) { return value(); }
};

template<>
struct DataType< ::franka_msgs::error_recovery > {
  static const char* value()
  {
    return "franka_msgs/error_recovery";
  }

  static const char* value(const ::franka_msgs::error_recovery&) { return value(); }
};


// service_traits::MD5Sum< ::franka_msgs::error_recoveryRequest> should match 
// service_traits::MD5Sum< ::franka_msgs::error_recovery > 
template<>
struct MD5Sum< ::franka_msgs::error_recoveryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::error_recovery >::value();
  }
  static const char* value(const ::franka_msgs::error_recoveryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::error_recoveryRequest> should match 
// service_traits::DataType< ::franka_msgs::error_recovery > 
template<>
struct DataType< ::franka_msgs::error_recoveryRequest>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::error_recovery >::value();
  }
  static const char* value(const ::franka_msgs::error_recoveryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_msgs::error_recoveryResponse> should match 
// service_traits::MD5Sum< ::franka_msgs::error_recovery > 
template<>
struct MD5Sum< ::franka_msgs::error_recoveryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::error_recovery >::value();
  }
  static const char* value(const ::franka_msgs::error_recoveryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::error_recoveryResponse> should match 
// service_traits::DataType< ::franka_msgs::error_recovery > 
template<>
struct DataType< ::franka_msgs::error_recoveryResponse>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::error_recovery >::value();
  }
  static const char* value(const ::franka_msgs::error_recoveryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_MSGS_MESSAGE_ERROR_RECOVERY_H
