urdf_path: /home/master/franka_ws/src/franka_modern_driver/franka_description/robots/panda_arm.urdf
base_frame_franka1: panda_link0
end_frame_franka1: tool
sim: false
low_pass_fliter: false
rcm_x_franka1: 0.44753
rcm_y_franka1: -0.00012277
rcm_z_franka1: 0.40912
rcmThreshold_franka1: 0.01
keyboard: /dev/input/event5
footswitch: /dev/input/event8
master: omega
usefootsitch: true

camera_in_base1_qx_franka1: 0
camera_in_base1_qy_franka1: 0
camera_in_base1_qz_franka1: 0
camera_in_base1_qw_franka1: 1
camera_in_base1_x_franka1: 0
camera_in_base1_y_franka1: 0
camera_in_base1_z_franka1: 0

eye_hand_cooperation: false
rcm: false
